In [9]:
import numpy as np
import matplotlib.pyplot as plt
import bayespy
%matplotlib inline 

x0 = np.random.multivariate_normal([0, 0], [[2, 0], [0, 0.1]], size=50)
x1 = np.random.multivariate_normal([0, 0], [[0.1, 0], [0, 2]], size=50)
x2 = np.random.multivariate_normal([2, 2], [[2, -1.5], [-1.5, 2]], size=50)
x3 = np.random.multivariate_normal([-2, -2], [[0.5, 0], [0, 0.5]], size=50)

obs = np.vstack([x0, x1, x2, x3])

N = 200
D = 2
K = 4

from bayespy.nodes import Dirichlet, Categorical

alpha = Dirichlet(1e-5*np.ones(K), name = 'alpha') 
Z = Categorical(alpha, plates=(N,), name='z')

from bayespy.nodes import Gaussian, Wishart

mu = Gaussian(np.zeros(D), 1e-5*np.identity(D), plates=(K,), name='mu')
Lambda = Wishart(D, 1e-5*np.identity(D), plates=(K,), name='Lambda')

from bayespy.nodes import Mixture

Y = Mixture(Z, Gaussian, mu, Lambda, name='Y') #This is the object
Y.observe(obs) #and these are the model observations - the data.
    
Z.initialize_from_random()


In [10]:
print(mu)

mu ~ Gaussian(mu, Cov)
  mu = 
[[ 0.  0.]]
  Cov = 
[[[100000.      0.]
  [     0. 100000.]]]



In [16]:
print(Lambda)

Lambda ~ Wishart(n, A)
  n =
[ 2.]
  A =
[[[100000.      0.]
  [     0. 100000.]]]



In [17]:
print(Z)

z ~ Categorical(p)
  p = 
[[ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.